# Site settings
title: living a brand new life
email: tianli.xu@gmail.com
description: learn something new everyday
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tianlixu.github.io" # the base hostname & protocol for your site
twitter_username: tianlixu123
github_username:  tianlixu

# Build settings
markdown: kramdown
