# Site settings
title: "living a brand new life"
email: tianli.xu@gmail.com
description: "learn something new everyday"

# the subpath of your site, e.g. /blog/
baseurl: ""
# the base hostname & protocol for your site
url: "http://tianlixu.github.io"

# the subpath of your site, e.g. /blog/
baseurl: ""
# the base hostname & protocol for your site
url: "http://tianlixu.github.io"

twitter_username: tianlixu
github_username:  tianlixu

# Build settings
markdown: kramdown

Regeneration: true
