# Site settings
title: "living a brand new life"
email: tianli.xu@gmail.com
description: learn something new everyday
<<<<<<< HEAD

# the subpath of your site, e.g. /blog/
baseurl: ""
# the base hostname & protocol for your site
url: "http://tianlixu.github.io"

twitter_username: tianlixu123
=======
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tianlixu.github.io" # the base hostname & protocol for your site
twitter_username: tianlixu
>>>>>>> 540695045b094b6f3029e62849e17b3c6245c95f
github_username:  tianlixu

# Build settings
markdown: kramdown

Regeneration: true
